# Generated by Django 3.0.5 on 2020-05-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articolo',
            options={'verbose_name': 'Articolo', 'verbose_name_plural': 'Articoli'},
        ),
        migrations.AlterModelOptions(
            name='giornalista',
            options={'verbose_name': 'Giornalista', 'verbose_name_plural': 'Giornalisti'},
        ),
        migrations.AlterField(
            model_name='giornalista',
            name='cognome',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='giornalista',
            name='nome',
            field=models.CharField(max_length=20),
        ),
    ]
